######################################################################
# Automatically generated by qmake (3.0) Thu Oct 6 21:05:55 2016
######################################################################

QT += core
QT -= gui
QT += bluetooth

TEMPLATE = app
TARGET = DesktopANCS
CONFIG += console
CONFIG += c++11
CONFIG -= app_bundle
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    ancs.cpp

HEADERS += \
    ancs.h
